"""
Module provide all constants used in app
"""
SESSION_MESSAGE = "Prijavljeni ste kao - {} {}"
SEPARATOR = "-----------------------------------------------------------------"
MAIN_ENGINE = True
MANAGER_MAIN_ENGINE = True
SELLER_MAIN_ENGINE = True
SEARCH_EVENTS_ENGINE = True
WRONG_USERNAME_PASSWORD = "Unijeli ste pogresno korisnicko ime ili sifru."
WRONG_INPUT_OPTION = "Unijeli ste nepostojecu opciju. Pokusajte ponovo."
VALUE_ERROR_MESSAGE = "Greska u konvertovanju tipa. Pokusajte ponovo."
GOODBYE_MESSAGE = "Dovidjenja."
CHOSE_MENU_OPTION = "Izaberite opciju menija:"
SELLER_MENU = "1. {}\n2. {}\n3. {}\n4. {}\n"
SELLER_MENU_OPTION_1 = "Pregler projekcija"
SELLER_MENU_OPTION_2 = "Prodaja karata"
SELLER_MENU_OPTION_3 = "Prikazi prodate karte"
SELLER_MENU_OPTION_4 = "Izlaz"
MANAGER_MENU = "1. {}\n2. {}\n3. {}\n4. {}\n5. {}\n6. {}\n"
MANAGER_MENU_OPTION_1 = "Pretraga projekcije"
MANAGER_MENU_OPTION_2 = "Unos nove projekcije"
MANAGER_MENU_OPTION_3 = "Brisanje projekcije"
MANAGER_MENU_OPTION_4 = "Izmjena projekcije"
MANAGER_MENU_OPTION_5 = "Dodavanje korisnika"
MANAGER_MENU_OPTION_6 = "Izlaz"
CHOSE_SEARCH_EVENT_OPTION = "Pretrazi po:"
SEARCH_EVENTS_MENU = "1. {}\n2. {}\n3. {}\n4. {}\n5. {}\n6. {}\n"
SEARCH_EVENTS_OPTION_1 = "Prikazi sve"
SEARCH_EVENTS_OPTION_2 = "ID-u"
SEARCH_EVENTS_OPTION_3 = "Nazivu filma"
SEARCH_EVENTS_OPTION_4 = "Zanru"
SEARCH_EVENTS_OPTION_5 = "Sali prikazivanja"
SEARCH_EVENTS_OPTION_6 = "Izlaz"
NOT_IMPLEMENTED = "Nije implementirano."
USER_NAME = "Korisnicko ime: "
USER_PASSWORD = "Sifra: "
SYSTEM_MESSAGE = "Molimo Vas da se ulogujete na sistem."
